version: '3.7'
services:
  interview-exercise:
    image: node:lts
    ports:
      - '5004:3000'
    volumes:
      - '.:/home/node/app'
    working_dir: /home/node/app
    command: 'bash -c "yarn && yarn dev"'